### PR TITLE
Add entities to world + basic desires for #27

### PR DESCRIPTION
**Pull request by kolinkrewinkel**
Will try to submit my updates every night, since we're on opposite time zones. This adds the entities to the world (though they duplicate, will need to remove all on disable or something.) Also creates desires in JSON, though priority is unimplemented and it does not reassemble them from string class construction.

Example:

``` json
"desires": [
      {
        "desireName": "DesireSwim",
        "priority": 0,
        "type": 4
      },
      {
        "desireName": "DesireLookRandomly",
        "priority": 0,
        "type": 3
      },
      {
        "desireName": "DesireLookAtNearest",
        "priority": 0,
        "type": 0
      }
```

### CODE REVIEW

**Comment by kumpelblase2** [comment]
Type is not necessary, they are set automatically in the desire itself.
Also, I don't want to add the entities again in the manager when the get created by the serializer. The reason is that createEntity() in the manager also adds them to the manager and thus the method in the serializer should do the same (which is currently already the case.)

**Comment by kolinkrewinkel** [comment]
Alright, will revise later.

**Comment by kolinkrewinkel** [comment]
There's some unneeded complexity in this now, as well as a few things unimplemented (namely priority), however I think this'll give us a good starting point for handling Desire saving. From here, I'm thinking changing the array to a custom object which has a type and class attribute, as well as a convenience method to convert from string to the proper object, so there's not a bunch of if() in the iteration, it gets put on the one method. As an example of it getting complicated, adding DesireLookAtNearest would need new code to handle having classes and floats.

**Comment by kolinkrewinkel** [comment]
I'm improved my implementation a lot, but am currently stuck on this: http://k.krwnk.me/MSwA Reflection doesn't like me passing in (I've even manually tried substituting the object to EntityHuman.class at runtime) a class to the first item in the log, which is/requires java.lang.Class<? extends... 

Any ideas? I had to break down and also not archive and rely on what is basically guess work, because I couldn't figure out how to archive/unarchive and retrieve based on a parameterized type.

**Comment by kolinkrewinkel** [comment]
On second thought, unless you guys have a solution, I think I'll switch away from constructors and add a method similar to the YML specific method that you have on the EntityData. Easy to implement and for third parties to add customization, and now the hard part of figuring out how to create the real properties is done - and not deal with the complexities and delicateness of Reflection.

**Comment by kumpelblase2** [comment]
I've been working around a solution which you were aiming at. I'm not really that far, nor do I have any idea if it will work or not. I have no problem if you'd go a different way and I'll see what you will come up with.

**Comment by kolinkrewinkel** [comment]
Good deal. Two of three solutions is better than one, especially because the best is likely a hybrid of them. Looking back, I don't like constructors. Not a fan of those kind of runtime operations. Passing it off to the class and having it be hard-coded by the dev/us to restore to an already hard-coded encode/serialization makes more sense.

**Comment by kumpelblase2** [comment]
did some more work: https://github.com/kumpelblase2/Remote-Entities/commit/49fbe65168d7a12efb54fb0d908cdc106b9f024e

**Comment by kumpelblase2** [comment]
I guess since all has been finished by me I can close this right?

**Pull request closed without merging**
