### PR TITLE
Persistence Fixes

### PR DESCRIPTION
**Pull request by kolinkrewinkel**
This fixes many things.

:white_check_mark:  Issues Fixed :white_check_mark: 
- `pathfindingRange` range being cast to an Integer, when 1) it isn't one in the data and 2) it isn't being assigned to one.
- NPE when doing a `toArray` on null `entitydata`
- Logging of all parameter data classes on deserialization
- Persisting a parameter with `-1` as its `pos`.

### CODE REVIEW

**Comment by kumpelblase2** [comment]
I appreciate your PRs and effort you put into the fixes, but it would be really nice if you could follow my coding style (https://github.com/kumpelblase2/Remote-Entities/wiki/Code-Style). Thank you.

**Comment by kolinkrewinkel** [comment]
I'll remember to check it next time. I'm not used to this language nor its coding style so I'm definitely not skilled in this department. Thanks for the quick responses. :smile:

**Comment by kumpelblase2** [comment]
Well, my coding style is unique and completely different from the java conventions, so it's all fine :)

**Comment by kolinkrewinkel** [comment]
Hehe. The other problem I was noticing (and corrected a couple of times, but not all) was IDEA completely indenting wrong. Will need to play with it.

**Comment by kumpelblase2** [comment]
hmm... interesting, it works fine for me (using IDEA too)

**Pull request merged**
