### PR TITLE
setMaxHealth remove

### PR DESCRIPTION
**Pull request by IDragonfire**
setMaxHealth has been removed ...

### CODE REVIEW

**Comment by IDragonfire** [comment]
Atm DamageBehavior is useless, or did I miss something?
I add these to detect NPC damage, so I must not listen to all EntityDamageEvents:
https://github.com/IDragonfire/DragonAntiPvPLeaver/blob/7b6944763a125a6976e95a9f3f4069a5f5e7f9e7/com/github/idragonfire/DragonAntiPvPLeaver/DNPCManager.java#L52

**Comment by IDragonfire** [comment]
Yes, that is the benefit, I must not listen to all EntityDamageEvents and get directly the RemoteEntity ...
I have no idea if the DamageBehavior is faster ...

**Comment by IDragonfire** [comment]
So I think to hold the library small, it is also k to remove this Behavior ...
The creation of objects (event and behavior) for each npc should be very inefficient and you must update it for any new mc version. Btw there should be note, that you can only add one behavior type per entity.

**Comment by kumpelblase2** [comment]
"Btw there should be note, that you can only add one behavior type per entity."
Isn't this obvious? However, making a note in the javadocs.

Moreover, I'm gonna close this.

**Pull request closed without merging**
