### PR TITLE
Update RemotePlayer.java

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kumpelblase2** [comment]
Well this does not place the npc in the bed 'physically' which I don't really like so much...

**Comment by ghost** [comment]
Well at least its a fix

just trying to help

**Comment by kumpelblase2** [comment]
Moreover you can't cast a Location to an int, which would make it more broken than it already is. You'd also screw over the users because you changed the method declaration.

**Comment by ghost** [comment]
Yes you can cast a Location to a int

**Comment by ghost** [comment]
ill change it a bit more then

**Comment by kumpelblase2** [comment]
"Yes you can cast a Location to a int" This is wrong. int is a primitive and Location is a class, that just doesn't work at all. Location also isn't a subclass of int nor is int a subclass of Location, that's not how it works.

**Pull request closed without merging**
