### PR TITLE
MC1.4.6 - biggest part done

### PR DESCRIPTION
**Pull request by Lolmewn**
Most of it is done.
I have renamed all packages in all files, the only thing left to change is the actual methods that changed with the update.
Hope this is of any use to you, if it isn't, ignore this :P
Note: there are a lot of errors in here.

### CODE REVIEW

**Comment by Lolmewn** [comment]
Damn, I forgot to commit the pom.xml with it.
The only change in there is from R0.2 to R0.1-SNAPSHOT for the bukkit dependency.

**Comment by kumpelblase2** [comment]
New method names would be a lot better. I just need to run my script to updated the package names... I'll try to note down all the changes today so there should be a working version this evening/tomorrow.

**Comment by Lolmewn** [comment]
Ah, right. Never mind then!

**Comment by kumpelblase2** [comment]
Actually, there were really not that many changes. No method changes to be precise. That's nice.

**Pull request closed without merging**
