### PR TITLE
Updates for 1.7.9

### PR DESCRIPTION
**Pull request by Doridian**
Including the properties on GameProfile etc (using correct UUIDs to avoid everyone being Steve)

### CODE REVIEW

**Comment by kumpelblase2** [comment]
May you be so kind and reformat the spawn code to match my convention(s)? https://github.com/kumpelblase2/Remote-Entities/wiki/Code-Style

I would greatly appreciate that.
If that's too much work for you to set up, you can tell me.

**Comment by Doridian** [comment]
I now edited things so that they _should_ match your code style rules.
If anything else needs changing, let me know.

**Comment by kumpelblase2** [comment]
Still some instances where it's wrong but that's good enough.
Thanks for the PR!

**Comment by Doridian** [comment]
You might also want to rename the branch or something, sometime.
//EDIT: And rebase it on master for your LICENSE changes.

**Pull request merged**
